[[redirects]]
	from = "https://blevins.netlify.com/*"
	to = "https://zending.us/:splat"
	status = 301

[[redirects]]
	from = "https://focused-bhabha-6e5ce0.netlify.com/*"
	to = "https://zending.us/:splat"
	status = 301